[pytest]
# marks
markers = 
    validate_csv: Tests related to validating the CSV file structure and content

# python_files
python_files = test_*.py

# addopts
addopts = --strict-markers --tb=short

rp_endpoint = https://reportportal.epam.com
rp_project = SOFIIA_ZINIUK_PERSONAL
rp_api_key = automation-reportportal-token_SOTub74ISTysPnpsCCoqKsLO0r_YL3VnmBKKGa1kMsNEah_61uhf6LtpgMquG79Q
rp_launch = My_First_Launch
; rp_enable = True
rp_log_batch_size = 20

; automation-reportportal-token

